sudo: required
language: node_js
services:
- docker
node_js:
- 'lts'
notifications:
  email:
  - howardc93@gmail.com
  - aqc2109@columbia.edu
script:
- sudo bash scripts/build.sh
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: scripts/postbuild.sh
