language: node_js
node_js:
- '0.10'
notifications:
  email:
  - howardc93@gmail.com
  - aqc2109@columbia.edu
services:
- mongodb
- redis-server
env:
- SESSION_SECRET=somesecretvalue ROOT_URL=http://localhost:5000 START_SEQ_NUM=AUTO RETRIEVER_HOST=http://localhost:5200 NODE_ENV=test PORT=5000 STEAM_USER=user1,user2 STEAM_PASS=pass1,pass2 STEAM_GUARD_CODE=""
script: "npm run fulltest"