language: node_js
node_js:
- '0.10'
notifications:
  email:
  - howardc93@gmail.com
  - aqc2109@columbia.edu
services:
- mongodb
- redis-server
env:
- SESSION_SECRET=travisci
- secure: W1DioR2KX0RbvQsmUXpOhVShE+CT/W8O/IlYEdil4Sn7VVcRD5qyw+ejehTbtWzhzhKe938K5QGVkNbUhukUZLAgV71r08Dz/c+tUowtx3+DZg+AXkLtQg6M0dQgON9armdQwa9xTZ+FjwBXaTbQJ56ea/lP1pmftnhp967uQTM=
deploy:
  provider: heroku
  api_key:
    secure: hALpeJGfMD7A+7HfndHiyhPG6ig2CDa1+st/VYgICHhJ++EC8dwn/Cu2ElejmNTZ6sw0gSEpe8zkprCIxHnXvMMuhyYjfr9Ts9NJz/iv8KaVHvDki4JZdx7ceY8LSNFEYEx4Y6Jvo+uzmmMZH5dcYSpd1LLjZRl917AuLUEJU/U=
