sudo: required
language: node_js
services:
- docker
node_js:
- 'node'
notifications:
  email:
  - howardc93@gmail.com
  - christian@paral.in
  - aqc2109@columbia.edu
before_install:
install: true
before_script:
- sudo bash scripts/prebuild.sh
script:
# run test outside container
#- npm run test && (npm run coveralls || true)
# run test inside container
- docker run -e "COVERALLS_SERVICE_NAME=travis-ci" -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN --net=host -i yasp/yasp sh -c 'npm run test && (npm run coveralls || true)'
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: scripts/postbuild.sh
