# You don't usually need to edit this file.
# If it does not fit your personal use case, docker-compose.override.yml is a preferred way to go.

version: '2'
services:
  db:
    build:
      context: .
      dockerfile: docker/postgres.dockerfile
    network_mode: host
  cassandra:
    build:
      context: .
      dockerfile: docker/cassandra.dockerfile
    network_mode: host
  cache:
    image: redis:3
    network_mode: host
  parser:
    image: yasp/parser
    network_mode: host
  web:
    build: .
    # 'basic' to launch basic configuration as in profiles/basic.json
    # 'full' to launch all the services as in profiles/full.json
    # 'custom-profile' to launch all services as in profiles/custom.json (you'll have to provide it)
    # or just override the whole command with your script if existing does not fit your needs
    command: ./docker/main-launch.sh basic 
    ports:
      - "5000"
    volumes:
      - .:/usr/src/yasp
    network_mode: host
    depends_on:
      - db
      - cache
      - parser
