# You don't usually need to edit this file.
# If it does not fit your personal use case, docker-compose.override.yml is a preferred way to go.

version: '2'
services:
  postgres:
    image: postgres:9.5
    container_name: odota-postgres
    environment:
      POSTGRES_PASSWORD: postgres
  postgresinit:
    image: postgres
    depends_on:
      - postgres
    volumes:
      - .:/usr/src
    container_name: odota-postgresinit
    entrypoint:
      [
        'bash',
        '-c',
        'sleep 30 && psql --file /usr/src/sql/init.sql postgres://postgres:postgres@odota-postgres/postgres && psql --file /usr/src/sql/create_tables.sql postgres://postgres:postgres@odota-postgres/yasp',
      ]
  cassandra:
    image: cassandra:4
    container_name: odota-cassandra
    environment:
      MAX_HEAP_SIZE: 128M
      HEAP_NEWSIZE: 24M
  cassandrainit:
    image: cassandra
    depends_on:
      - cassandra
    volumes:
      - .:/usr/src
    container_name: odota-cassandrainit
    entrypoint:
      [
        'bash',
        '-c',
        'sleep 75 && cqlsh -f /usr/src/sql/init.cql odota-cassandra && cqlsh -f /usr/src/sql/create_tables.cql -k yasp odota-cassandra',
      ]
  scylla:
    image: scylladb/scylla:5.4
    container_name: odota-scylla
  scyllainit:
    image: scylladb/scylla
    depends_on:
      - scylla
    volumes:
      - .:/usr/src
    container_name: odota-scyllainit
    entrypoint:
      [
        'bash',
        '-c',
        'sleep 60 && cqlsh -f /usr/src/sql/init.cql odota-scylla && cqlsh -f /usr/src/sql/create_tables.cql -k yasp odota-scylla',
      ]
  redis:
    image: redis:6
    container_name: odota-redis
  elasticsearch:
    image: elasticsearch:6.8.23
    container_name: odota-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - bootstrap.system_call_filter=false
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  parser:
    image: odota/parser
    container_name: odota-parser
  core:
    build:
      context: .
      dockerfile: Dockerfile
    image: odota/core
    # Override this command with your script if existing does not fit your needs
    entrypoint: bash docker/main-launch.sh
    ports:
      - '5000:5000'
      - '5100:5100'
    environment:
      PARSER_HOST: http://odota-parser:5600
      POSTGRES_URL: postgresql://postgres:postgres@odota-postgres/yasp
      READONLY_POSTGRES_URL: postgresql://readonly:readonly@odota-postgres/yasp
      REDIS_URL: redis://odota-redis:6379/0
      CASSANDRA_URL: cassandra://odota-cassandra/yasp
      SCYLLA_URL: scylla://odota-scylla/yasp
      ELASTICSEARCH_URL: odota-elasticsearch:9200
    volumes:
      - .:/usr/src
    links:
      - postgres
      - cassandra
      - redis
      - elasticsearch
      - parser
      - scylla
    container_name: odota-core
