apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
    tier: infra
  name: cassandra
spec:
  ports:
    - port: 9042
  selector:
    app: cassandra
    tier: infra
----
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: cassandra
    tier: infra
  name: cassandra
  namespace: yasp
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: cassandra
        tier: infra
    spec:
      containers:
        - command:
            - /run.sh
          resources:
            requests:
              cpu: "1m"
              memory: "8G"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: gcr.io/google_containers/cassandra:v6
          name: cassandra
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          volumeMounts:
            - mountPath: /cassandra_data
              name: cassandra
      volumes:
        - name: cassandra
          persistentVolumeClaim:
            claimName: cassandra
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cassandra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100
----
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cassandra-1
spec:
  capacity:
    storage: 100
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: "cassandra-1"
    fsType: "ext4"
----
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cassandra-2
spec:
  capacity:
    storage: 100
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: "cassandra-2"
    fsType: "ext4"
----
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cassandra-3
spec:
  capacity:
    storage: 100
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: "cassandra-3"
    fsType: "ext4"
