name: docker-compose-actions-workflow
on: 
  push:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        run: docker-compose -f docker-compose.ci.yml up -d && sleep 25 && docker ps -a && docker logs odota-core && docker exec -i odota-core sh -c 'npm run test'
      - name: Push to Docker
        if: github.ref == 'refs/heads/master'
        run: ./scripts/postbuild.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
