name: docker-compose-actions-workflow
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: docker-compose -f docker-compose.ci.yml up -d && sleep 30 && docker ps -a && docker logs odota-core && docker exec -i odota-core sh -c 'npm run test'
      - name: Push to Docker
        if: github.ref == 'refs/heads/master'
        run: ./scripts/postbuild.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
